apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCQe2iFXykI1nA9s+kLv6HB3kb+0c6Ixdcj9tozpJ5CE1R8scucYCwRnkTXdJPkQVVJyfZXPj8czFPindASM0Ii0+2mQyJXHP8h8iqpfnBw/v5Da+FnUBHg7eqN0piS2uJcKSexMVYNeUTOgZ/MuDElmAYpj6WZyexdfLR08rR+LuCDxJ+oW7zKcXOYMvYLRXnXskkE/gkGBm1ysO6S9nF7yrp5BlygwT0rx1BtwIM5CWvgGeYyPu7nu2YT135zxmhhPeSoibgLFoikBTq+Cung/H7rqtjleuGcfNKD6QVurJtXyk3lIwjcYGLLc2acubQwnZcHi5QOBqpPTZZh7lBA+wJr6UgVOMUxda4JcxAV0DEnxUT71e7pcP93NziNLYvxRaGSW6w8chajmUqduFtH8HX/Quqb9SENIjBYPTvo/AhFTCFOPTnAbKiCP7xN9NtDLz3MpMXOFJVCYgkgzr1gUcWBolhVACIxucYDKAA18AC7F1bGoty1O+2Fl6eSfSREefP+qMN4acIBKR5Iz1Dw+uDkHTQcGAEVoHuPOV7a1zRo4XpMA2xORaLW5Xj62IZCPp4Fp7/+JAhvYrzP8z2oP73UfWz/6wOXhOoYX2NW4xrmK3LS0dMd4nu9NvtUqNauaWB8YG8jmOifrHE1CPx8gXR2j8aIOh+5gB0RiGNLOibg0YQwX9PlLUsqsFVuP7M13n/BPHkB0A==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

