# Source: ibm-ssp-engine/templates/pre-rollback.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-ibm-ssp-engine-prerollback
  labels:
    app.kubernetes.io/name: ibm-ssp-engine
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: ibm-ssp-engine-1.2.3
    release: release-name
  annotations:
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "release-name"
      labels:
        app.kubernetes.io/name: ibm-ssp-engine-prerollback
        app.kubernetes.io/instance: release-name-prerollback
        app.kubernetes.io/managed-by: Helm-prerollback
        helm.sh/chart: ibm-ssp-engine-1.2.3-prerollback
        release: release-name-prerollback
      annotations:        
        productID: "9b921dda8dd141bf8869ead1a790d4da"
        productName: "IBM Sterling Secure Proxy Certified Container"
        productVersion: "6.3.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
    spec:
      serviceAccountName: release-name-ibm-ssp-engine-serviceaccount
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups:
        - 5555
      affinity:        
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:      
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:        
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  
          preferredDuringSchedulingIgnoredDuringExecution:        
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  
          preferredDuringSchedulingIgnoredDuringExecution:
      restartPolicy: Never
      containers:
        - name: post-rollback-job
          image: "cp.icr.io/cp/ibm-ssp-engine/ssp-engine-docker-image:6.0.3.0.02"
          imagePullPolicy: IfNotPresent
          env:
          - name: SUPPLEMENTAL_GROUP
            value: ""
          command: ["/spinstall/maintenance.sh", "rollback"]
          volumeMounts:
            - mountPath: /spinstall/IBM/SP
              name: engine-pvc
              subPath: ENGINE
            - mountPath: /spinstall/backup
              name: engine-pvc
              subPath: ENG_BACKUP
          securityContext:
            
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - CHOWN
              - SETGID
              - SETUID
              - FOWNER
              - DAC_OVERRIDE
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsUser: 1000
          resources:
            limits:
              cpu: 1000m
              ephemeral-storage: 6Gi
              memory: 3Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 4Gi
              memory: 3Gi
      volumes:
      - name: engine-pvc
        persistentVolumeClaim:
          claimName: release-name-ibm-ssp-engine-pvc